homesengland/he-pipeline-assessment

src/Elsa.CustomActivities/Activities/MultipleChoice/MultipleChoiceQuestion.cs, src/Elsa.CustomActivities/Activities/MultipleChoice/MultipleChoiceQuestionBookmark.cs, src/Elsa.CustomActivities/Activities/MultipleChoice/MultipleChoiceQuestionBookmarkProvider.cs, src/Elsa.CustomActivities/Activities/MultipleChoice/MultipleChoiceQuestionInvoker.cs, src/Elsa.Models/MultipleChoiceQuestionModel.cs, src/Elsa.Server/Controllers/WorkflowController.cs, src/Elsa.Server/Data/Migrations/20220817100524_RemoveQuestionID.Designer.cs, src/Elsa.Server/Data/Migrations/20220817100524_RemoveQuestionID.cs, src/Elsa.Server/Endpoints/MultipleChoice/MultipleChoiceQuestionController.cs, src/He.PipelineAssessment.UI/HttpClients/ElsaServerHttpClient.cs
Co-authored-by: Jerry Zajac 32240008+jarekzaj@users.noreply.github.com
Co-authored-by: Jonny T 90678699+Jonnythan-t@users.noreply.github.com
Co-authored-by: Lorna B <93874097+lornacbirchall@users.noreply.github.com>
=> Removed Question ID from Multichoice activity and database

src/Elsa.CustomActivities/Activities/QuestionScreen/QuestionScreen.cs
Small change to wording as requested by Product Owner, before it gets to the user testing stage to avoid confusion.
Changed the description on the new Question Screen from  "multi question screen" to "Set up a question screen"
=> Wording change for activity

src/Elsa.Dashboard/src/components.d.ts, src/Elsa.Dashboard/src/components/question-components/elsa-checkbox-component.tsx, src/Elsa.Dashboard/src/components/question-components/elsa-question-component.tsx, src/Elsa.Dashboard/src/components/question-components/elsa-radio-component.tsx, src/He.PipelineAssessment.UI/Features/Workflow/Views/_QuestionScreen.cshtml
Minor UI changes to fix spacing issues and terminology within Elsa.
Updated the Question Screen page in the UI to add in a little padding between the final question, and the Save and Continue button.
Changed the "Title" label in Elsa to be more indicative of it's actual (Current) use, to be Question Name.  Title is suggestive that it is displayed on the front end, which it currently is not.
Co-authored-by: Rob Ryan [112186767+rryan0088@users.noreply.github.com](mailto:112186767+rryan0088@users.noreply.github.com)
=> Bugfix/minor UI issues

src/He.PipelineAssessment.UI.Tests/Helper/CurrencyHelperTests.cs, src/He.PipelineAssessment.UI/Features/Workflow/Views/Shared/_ReviewAnswers.cshtml, src/He.PipelineAssessment.UI/Features/Workflow/Views/_CurrencyQuestion.cshtml, src/He.PipelineAssessment.UI/Helper/CurrencyHelper.cs, src/He.PipelineAssessment.UI/wwwroot/js/site.js
Currency comma separated for question answers.
=> Currency comma separated for question answers

src/Elsa.Server.Tests/Features/Workflow/Helpers/ElsaCustomModelHelperTests.cs, src/Elsa.Server.Tests/Features/Workflow/StartWorkflow/StartWorkflowCommandHandlerTests.cs, src/Elsa.Server/Features/Workflow/StartWorkflow/StartWorkflowCommandHandler.cs, src/Elsa.Server/Helpers/ElsaCustomModelHelper.cs
updated start workflow to throw when the runresult comes back with an exception
=> added default name for activity name when it is not set in dashboard

src/He.PipelineAssessment.Data/VFM/EsriVFMResponse.cs
, as they don't have values for national projects
=> updating two vfm datasource fields to nullable

src/Elsa.Dashboard/Dockerfile, src/Elsa.Server/Dockerfile, src/He.PipelineAssessment.Data/VFM/EsriVFMResponse.cs, src/He.PipelineAssessment.UI/Dockerfile
Hotfix Update from release 1.1.1 into release 1.2
=> Release 1.1.1

src/Elsa.CustomInfrastructure/Elsa.CustomInfrastructure.csproj, src/Elsa.CustomWorkflow.Sdk/Elsa.CustomWorkflow.Sdk.csproj, src/Elsa.Dashboard/ElsaServerController.cs, src/Elsa.Server/Elsa.Server.csproj
* Initial fixes copied from other branch.
* Initial attempt at adding access token controls for Elsa Server
* added SqlClient to Elsa CustomInfrastructure lib
* removed reference to System Data Sql Client
* added azure identity package and azure core to elsa custom infrastructure
---------
=> Hotfix/workload identity upgrade (#298)

src/He.PipelineAssessment.UI/Common/Utility/AssessmentToolWorkflowInstanceHelpers.cs
This PR fixes the problem to load confirmation screen on using Test Summary to test a work flow in PAS
=> 91714 Handling ConfirmationScreen to Load On Test Summary Url Use

src/Elsa.Dashboard/Pages/_DataDictionaryRecord.cshtml, src/Elsa.Dashboard/Pages/_DataDictionaryRecord.cshtml.cs
This PR holds the fix for data Dictionary Update and Archive
=> 92922 Fix to Data Dictionary Update And Archive

src/He.PipelineAssessment.Data/SinglePipeline/EsriSinglePipelineClient.cs
This PR holds changes to ignore the project of Place type being loaded into PAS
=> 92922 Ignored Place Projects from Loading into PAS

src/He.PipelineAssessment.UI/Views/Shared/_Layout.cshtml, src/He.PipelineAssessment.UI/Views/Shared/_LayoutFullWidth.cshtml
This PR handles the form Submission and disable button on click event occurance
=> 93158 Handle Form Submission and button Disable on Submit

src/He.PipelineAssessment.Infrastructure/Data/PipelineAssessmentContext.cs, src/He.PipelineAssessment.Infrastructure/UserProvider.cs, src/He.PipelineAssessment.Models/ViewModels/SyncModel.cs, src/He.PipelineAssessment.UI.Tests/Services/AutoSyncBackgroundServiceTest.cs, src/He.PipelineAssessment.UI/Features/SinglePipeline/Sync/SyncCommandHandler.cs, src/He.PipelineAssessment.UI/Features/SinglePipeline/Views/Sync.cshtml, src/He.PipelineAssessment.UI/Program.cs, src/He.PipelineAssessment.UI/Services/AutoSyncBackgroundService.cs
This Service helps pass to load data into PAS every hour automatically with out asking users to sync
=> Feature/81576 Back Ground Process Service to auto sync

src/He.PipelineAssessment.UI/Features/Admin/Views/LoadAssessmentToolWorkflow.cshtml
load assessment configuration with new attributes
=> Load Assessment Configurations

src/Elsa.CustomInfrastructure/Elsa.CustomInfrastructure.csproj, src/Elsa.CustomWorkflow.Sdk/Elsa.CustomWorkflow.Sdk.csproj, src/He.PipelineAssessment.Data/He.PipelineAssessment.Data.csproj
Updated Package to Remove vulnerability
=> Identity Pacakge Vulnerability Update

src/He.PipelineAssessment.Infrastructure/Config/AssessmentConfiguration.cs, src/He.PipelineAssessment.Infrastructure/Migrations/20240422152708_SpIdIndex.Designer.cs, src/He.PipelineAssessment.Infrastructure/Migrations/20240422152708_SpIdIndex.cs, src/He.PipelineAssessment.Models/Assessment.cs, src/He.PipelineAssessment.Models/He.PipelineAssessment.Models.csproj, src/He.PipelineAssessment.UI/Features/SinglePipeline/Sync/SyncCommandHandler.cs
=> Release 1.2.1

src/Elsa.Server/Features/Workflow/LoadQuestionScreen/LoadQuestionScreenRequestHandler.cs
This PR holds an enhancement to the existing behaviour to give user the ability to enter the value when the read only field null values
=> 81270 Allow Edits of Pre-Populated fields, if the answer is empty

src/He.PipelineAssessment.UI/Integration/ServiceBusSend/GetAssessmentDTOCommandHandler.cs
This PR holds changes to handle the Test summary confirmation load and Start Now Button functionality
=> Test Summary Feature Issue Fix

src/He.PipelineAssessment.UI.Tests/Features/Admin/AdminControllerTests.cs, src/He.PipelineAssessment.UI/Features/Admin/AdminController.cs, src/He.PipelineAssessment.UI/Features/Admin/Views/AssessmentToolWorkflow.cshtml, src/He.PipelineAssessment.UI/Features/Admin/Views/DeleteAssessmentToolWorkFlow.cshtml, src/He.PipelineAssessment.UI/Features/Admin/Views/LoadCategories.cshtml
Warning Error Message On Clicking Remove of work flow definition
=> Added Warning Error Message On Remove

src/Elsa.CustomActivities/Providers/ScoreProvider.cs, src/Elsa.CustomInfrastructure/Elsa.CustomInfrastructure.csproj, src/Elsa.CustomWorkflow.Sdk/Elsa.CustomWorkflow.Sdk.csproj, src/Elsa.Server/Features/Workflow/LoadQuestionScreen/LoadQuestionScreenRequestHandler.cs, src/He.PipelineAssessment.Data/He.PipelineAssessment.Data.csproj, src/He.PipelineAssessment.UI/Integration/ServiceBusSend/GetAssessmentDTOCommandHandler.cs, src/He.PipelineAssessment.UI/Integration/ServiceBusSend/ServiceBusMessageSender.cs
This merge is part of hot fix  for array values . 
NOTE: Vulnerability is raised as has been addressed as part of this
=> hotfix 1.2.1

src/He.PipelineAssessment.UI/azure-pipelines-build-semver.yml
=> Set correct Ref

src/Elsa.Dashboard/azure-pipelines-build.yml, src/Elsa.Server/azure-pipelines-build.yml
=> Nightlies + Alias change

.github/workflows/codeql.yml, src/He.PipelineAssessment.UI/azure-pipelines-build-semver.yml
Added CodeQL.yaml to enable code scanning in repository.
=> Add codeql.yml to enable code scanning

src/Elsa.Dashboard/package-lock.json, src/Elsa.Dashboard/package.json, src/He.PipelineAssessment.UI/azure-pipelines-build-semver.yml
Updated puppeteer version to resolve vulnerability in ws package.
=> Updated puppeteer version

src/Elsa.Dashboard/package-lock.json, src/Elsa.Dashboard/package.json, src/He.PipelineAssessment.UI/azure-pipelines-build-semver.yml
Updating node package to address Axios CSRF vulnerability
=> Updating node package to address Axios CSRF vulnerability

src/Elsa.Dashboard/azure-pipelines-build.yml, src/Elsa.Server/azure-pipelines-build.yml, src/He.PipelineAssessment.UI/azure-pipelines-build-semver.yml
Space out nightly schedule test
=> Space out nightly schedule test

src/Elsa.Dashboard/Pages/_Layout.cshtml, src/Elsa.Dashboard/Pages/_LayoutFullWidth.cshtml, src/He.PipelineAssessment.UI/Views/Shared/_Layout.cshtml, src/He.PipelineAssessment.UI/Views/Shared/_LayoutFullWidth.cshtml, src/He.PipelineAssessment.UI/azure-pipelines-build-semver.yml
Added Signout links to PAS and Elsa
=> Sign out link on Pipeline assessment and Elsa pages

src/He.PipelineAssessment.UI/Features/Assessment/Views/Summary.cshtml, src/He.PipelineAssessment.UI/azure-pipelines-build-semver.yml
Added Labels To Fields In Assessment Summary
Put into table for farmatting purposes
=> Adding Data Labels For Fields In Assessment Summary
